### ISSUE TITLE
Mistake in formula

### ISSUE THREAD

**Issue by maxshort** [e-maxx-eng/e-maxx-eng.github.io#11]
Thank you for this translation as this article has been very helpful to me. 

I think that there is a typo in the formula n⋅(1−1/(P1^a1))⋅(1−1/(P2^a2))⋅…⋅(1−1/Pk^ak). 

It looks like the step from the second to last line is to multiply everything by (n/<prime factorization of n>)

If this is the case, P1^(a1-1)/P1^(a1) should be P1^-1 or 1/P1

Thus the last formula should be n \* (1-1/p1)*(1-1/p2)...

**Comment by gabrielsimoes** [comment]
As of recent changes, this issue has no place here, as this is only a redirect page andnot the real translation project. It should be closed and (maybe) reopened at the other repository.

**Comment by jakobkogler** [comment]
I don't think this is still a problem any more.
